### PR TITLE
Add Javascript related resources

### PR DESCRIPTION
**Pull request by darrylhebbes**
Added links to JS3-mode, NodeJS-Repl Oh My Emacs Javascript

### CODE REVIEW

**Comment by kuanyui** [comment]
Please modify the form of config link like [Haskell](https://github.com/emacs-tw/awesome-emacs#haskell) ones.

**Comment by kuanyui** [comment]
Please fix your commit.

**Comment by darrylhebbes** [comment]
@kuanyui I am not sure what you mean, they are like the Haskell ones.... they are links in Markdown... and they work - right?

**Comment by kuanyui** [comment]
Sorry, I mean create a quote block `External Guides` (like `Haskell`) and put the `Oh My Emacs JavaScript` in it because it's a tutorial, not a package.

**Pull request closed without merging**
