### PR TITLE
Create AI / Machine Learning Section and add Landmark learning neural…

### PR DESCRIPTION
**Pull request by metaperl**
Add [landmark](http://elpa.gnu.org/packages/landmark.html) to Awesome Emacs.

### CODE REVIEW

**Comment by metaperl** [comment]
I am the original author of this source code. I wrote it as part of my assignments in  a class on Brain
Theory and Neural Networks at the University of Southern California. It is based on the paper "Landmark Learning: An Illustration of Associative
Search"  authored by Andrew G. Barto and Richard S. Sutton and
published to Biological Cybernetics in 1981.

**Comment by kuanyui** [comment]
I think that is away from the point and not a reason that should create a new category "AI / Machine Learning" for it. It's still a game.

For example, consider that Adobe has API-powered selection tools in their Photoshop, it's still called an image editing application, and should still be seem as a "graphics related application" instead of "Machine Learning Whatever".

https://www.emacswiki.org/emacs/CategoryGames

**Comment by metaperl** [comment]
> It's still a game.

What makes you think it is a game? I'm going to go ahead and create a different pull request to place it under "Fun", but I'd like to know what makes you think it is a game.

**Comment by metaperl** [comment]
The commit which created a new section has been reverted. A new commit which places it as the bottom of the Fun section has been pushed.

**Comment by kuanyui** [comment]
> > It's still a game.
> 
> What makes you think it is a game? I'm going to go ahead and create a different pull request to place it under "Fun", but I'd like to know what makes you think it is a game.

The author wrote in ELPA: `Landmark is a relatively non-participatory game`. And it's also in [Emacs wiki](https://www.emacswiki.org/emacs/CategoryGames) .

**Pull request merged**
