### PR TITLE
add Elbank

### PR DESCRIPTION
**Pull request by azzamsa**

### CODE REVIEW

**Comment by agsdot** [comment]
@azzamsa, can you edit this PR to link to https://github.com/NicolasPetton/elbank.

I think previously @NicholasPetton had indium / jade only on gitlab and then he put it on github as well.

I’m guessing that sharing the github repo url for elbank (which btw also references the gitlab url) will be conducive to github activity that encourages and assists development of the project (e.g pull requests, issues, github starring, etc).

Thanks!

**Comment by NicolasPetton** [comment]
Yes, I'm mirroring all my projects on GitHub, because that's where the community is, so I'm also in favor of a link to the GitHub repo.

**Comment by agsdot** [comment]
:+1: @NicolasPetton .

I was guessing that -- you were posting on both gitlab and then github for the purpose of "that's where the community is" and to encourage more contributions, etc.

Thanks for the work on the multiple packages you work on (e.g. seq.el, indium, elbank, etc).

**Comment by azzamsa** [comment]
changed the link

**Comment by agsdot** [comment]
👍 @azzamsa , thanks for updating the link as well as the recent PR's.

**Comment by azzamsa** [comment]
Thank you so much for accepting my pr.
It's an honour to contribute to community.

@NicolasPetton Thanks for all your contribution to community.

@agsdot Thanks for maintaining this awesome repo well :)

Happy hacking.

**Comment by agsdot** [comment]
@azzamsa , really it's @kuanyui @Superbil @coldnew -- thank them for them creating and maintaining this awesome repo.

Happy hacking as well.

**Pull request merged**
