### PR TITLE
add various packages and stop quoting table of contents

### PR DESCRIPTION
**Pull request by rahiel**
Also fix link for markdown-mode so github can show it properly. 

Edit: and I think the table of contents looks better outside a quoteblock, don't you think?

### CODE REVIEW

**Comment by rahiel** [comment]
The toc was quoted and had a [grey colour](https://github.com/emacs-tw/awesome-emacs/blob/995728eca61d84b67ec6f95f456a9dab4e1c2147/README.org). Now it's the normal text colour without the quote mark on the left.

**Comment by kuanyui** [comment]
In fact that is in purpose, just for that grey colour...

**Comment by rahiel** [comment]
Apologies! I never saw a toc grey like that, I mistakenly "fixed" it then...

**Comment by kuanyui** [comment]
reverted.

**Pull request merged**
