### PR TITLE
added renpy-mode

### PR DESCRIPTION
**Pull request by billywade**

### CODE REVIEW

**Comment by kuanyui** [comment]
What....? This should not place under multimedia...... Language -> Python instead.

**Comment by agsdot** [comment]
It’s also unmaintained. So I’m hesitant to add it here as well.

**Comment by agsdot** [comment]
Hi @billywade,

Your point about increasing visibility makes sense. 

I am attaching the URL to the associated /r/emacs reddit post for the sake of increasing some visibility about the converation about renpy-mode.

https://www.reddit.com/r/emacs/comments/98v83k/renpy_mode_for_editing_visual_novels_within_emacs/

Please clean up your previous commit.  A 

`#README.org#` work in progress Emacs file was unnecessarily added. Please remove that temp file.

**Comment by billywade** [comment]
@agsdot Just removed the file, thank you for noticing. I posted that, too, but I figured that adding it here and to MELPA would be more enduring.

**Comment by billywade** [comment]
Thanks!

**Pull request merged**
