### PR TITLE
Awesome bot

### PR DESCRIPTION
**Pull request by agsdot**

### CODE REVIEW

**Comment by agsdot** [comment]
@kuanyui, Issue #114 being open for so long was bothering me!  Finally got around to doing something about it.

- The awesome bot gem on a travis build now validates and checks the many links on README.org . With it I was able to find many redirects, stale links, lack of https links, duplicate links, and more. 
- I also put in some code to ensure that gen-toc.el would always be run. If the person that has put in a PR has created a new org bullet point but forgotten to run gen-toc, the travis build should error should indicate that gen-toc.el should have been evaluated.

Ok. Things I'm wondering on my part (I haven't delved too much into jenkins much less travis before -- this was a fun exercise). I activated travis for my agsdot/awesome-emacs repo on travis. I see on travis that emacs-tw has a travis account, but the toggle/permissions for travis to be activated on emacs-tw/awesome-emacs needs to be put in if it's going to work on the upstream repo.

Also, pinging @Superbil and @coldnew, and cc'ing you on the conversation. I'm assuming you three have access to emacs-tw admin rights on both github and travis. I'm guessing any of you could toggle the setting for travis.  

Thanks for the feedback. 

P.s. Please do give feedback on the .travis.yml file. I based most of it off of other awesome-bot .travis.yml file scripts, and also magit's [travis.yml](https://github.com/magit/magit/blob/master/.travis.yml) to build emacs and run gen-toc.el.

P.p.s. Also not sure as to benefits or difference of using awesome bot with travisci or circleci. Apparently awesome bot can be used with either (and also other CI systems). As long as emacs-tw has an account with any of them, I'd like to get the travis.yml / circle.yml file associated with it, so that awesome bot validation can run.

**Comment by agsdot** [comment]
Check out https://travis-ci.org/agsdot/awesome-emacs/builds for some of the builds. Some failing and some successful. 

Most of the failures were made as I was iterating on the .travis.yml file. Also, was using a couple git branches on my agsdot/awesome-emacs github repo. 

Right now, build 21 is failing because of hopefully a temporary issue with "https://www.typerex.org/" the site just stopped responding a couple hours ago. But in prior builds it was responding.

**Comment by coldnew** [comment]
Travis permission for `awesome-emacs` is open now :)

**Comment by Superbil** [comment]
I checked the travis script, look great. It will check diff very cool.

**Comment by coldnew** [comment]
@agsdot Could you also add the travis badge at the top of `README.org` ?

Just add following content after the `aweseome badge`:

```org
[[https://travis-ci.org/emacs-tw/awesome-emacs][file:https://travis-ci.org/emacs-tw/awesome-emacs.svg?branch=master]]
```

**Comment by agsdot** [comment]
@coldnew sure can do. 

Coincidentally / ironically enough, awesome bot discovered that one of those links needed to be updated.

[[https://travis-ci.org/emacs-tw/awesome-emacs][file:https://api.travis-ci.org/emacs-tw/awesome-emacs.svg?branch=master]] . It went from file:https://travis-ci.org to file:https://api.travis-ci.org . 

I'll bring in (merge? rebase? squash? -- I know that there has been a preference to use merging less frequently over the past year or so) the whole pull request soon.

**Comment by agsdot** [comment]
And it's good!

Here's the travis build number 1 he actual Pull Request https://travis-ci.org/emacs-tw/awesome-emacs/builds/299961682 .

Here's the subsequent rebase and merge, travis build number 2: https://travis-ci.org/emacs-tw/awesome-emacs/builds/299964033 . 

Travis for emacs-tw had it's first two successful builds.

**Comment by agsdot** [comment]
@coldnew , @kuanyui , @Superbil I just wanted to check in and see if the emacs-tw travis-ci is properly connected to the emacs-tw/awesome-emacs github repo.

I noticed that the last "Squash and merge" wasn't checked by travis

Screen Shot 2020-10-01 at 11 46 04 AM

Also, comparing travis for my downstream agsdot travis vs upstream emacs-tw travis, I noticed I no longer have the "Restart build" button. Just in the past few days, https://travis-ci.org/github/emacs-tw/awesome-emacs, has no longer been showing me the "Restart build" button . Only just a few days ago, I used to be able to re-trigger the build by pressing the "Restart build" button.

Screen Shot 2020-10-01 at 11 46 52 AM

**Pull request merged**
