### PR TITLE
Add some new library.

### PR DESCRIPTION
**Pull request by zw963**
1. Add emacs-winum
2.  Add move-dup (replace move-text completely)
3. Remove duplicate highlight-parentheses

### CODE REVIEW

**Comment by kuanyui** [comment]
The feature of highlight-parentheses is not the same with rainbow-delimiters. You should not remove it.

**Comment by kuanyui** [comment]
Why replace move-text with another one of less popularity?

**Comment by kuanyui** [comment]
Screenshot_20210912_115144
Wrong indentation....

**Comment by zw963** [comment]
> The feature of highlight-parentheses is not the same with rainbow-delimiters. You should not remove it.

Okay, revert it, though,  i am no see any different, and for highlight parentheses, if is emacs builtin feature?  i never need use this package anyway.

**Comment by zw963** [comment]
> Why replace move-text with another one of less popularity?

Because move-dup more awesome ? please try it, it can replace move-text compeletely,  and with more nice feature (use daily for me)

**Comment by zw963** [comment]
what we want is only awesome package, not all packages, or duplicate packages, right?

**Comment by kuanyui** [comment]
> > Why replace move-text with another one of less popularity?
> 
> Because move-dup more awesome ? please try it, it can replace move-text compeletely, and with more nice feature (use daily for me)

This is your personal preference, you're welcome to add, but should not remove the more popular one according to your personal preference. I also feel `company` has less bug than `auto-complete` but I won't remove it because too many people use it.


>>    The feature of highlight-parentheses is not the same with rainbow-delimiters. You should not remove it.
>
> Okay, revert it, though, i am no see any different, and for highlight parentheses, if is emacs builtin feature? i never need use this package anyway.

1. You apparently doesn't understand what `highlight-parentheses`  is doing. Please read README until understood. 
2. You don't need doesn't mean others doesn't either.

**Comment by zw963** [comment]
> You apparently doesn't understand what `highlight-parentheses` is doing. Please read README until understood.

Okay, agree



> This is your personal preference, you're welcome to add, but should not remove the more popular one according to your personal preference. 

popular is not the only measure standard, i thought this `awesome-emacs` project is recommended for `awesome`, `live maintain` and `useful feature rich`.

i never use `move-text` before, though it star is 117, more than move-dup, but that means nothing, many dead project have thousands stars.

 please check `move-text` melpa version, it is 20170909, move-dup is 20210127, move-dup more active development,  can replace former completely.

> I also feel company has less bug than auto-complete but I won't remove it because too many people use it.

this is totally not same case, because company can't replace AC completely, please check README for detail.

**Comment by zw963** [comment]
okay, i know highlight-parentheses does, though, i still think  rainbow-delimiters is a superset

**Comment by kuanyui** [comment]
A project without any update for a long time could be:

1. It remains lots of bugs without maintainer to fix.
2. It's stable enough.

If it's me, I would usually choose the one with more users when there are multiple libraries of same feature can be chosen and cannot decide which one is better or less bugs / stable enough. If there's no severe issue (for example, cannot run on latest Emacs), please don't remove old but popular package.
 
>>  I also feel company has less bug than auto-complete but I won't remove it because too many people use it.
>
>this is totally not same case, because company can't replace AC completely, please check README for detail.

I've used both for nearly 10 years, I am familiar with the features and bugs of them. And I also feel company is better for me and can replace auto-complete completely, as if you think move-dup is better for your requirements.

**Pull request merged**
