### PR TITLE
Add packages and updates

### PR DESCRIPTION
**Pull request by agsdot**

### CODE REVIEW

**Comment by agsdot** [comment]
@kuanyui I was wondering a couple things:

I added a reference to emacs-slack near where weechat.el was recently added. That area is categorized under IRC. However, neither weechat or slack are exactly IRC. Should this category be changed and broadened out to just be called "Chat"?  Or would "Messaging" be a more appropriate word -- chat seems a bit informal, or rather a bit 1990'ish.

Another thing, @kuanyui and @rakanalh, under what category should [emacs-dashboard](https://github.com/rakanalh/emacs-dashboard) go? I could see it fitting under various areas: Interface Enhancements, Project Management, Navigation? What do you think?

**Comment by kuanyui** [comment]
1. Feel free to create new category (as long as remember to generate TOC). `Chat` is OK I think.
2. I think `Interface Enhancements` is OK. Just my opinion: don't take it too serious. If someone think it's inappropriate, it can send a PR.

**Comment by agsdot** [comment]
Ok.

So are you suggesting 1) renaming the category IRC to Chat? Or 2) breaking up the category into the four IRC items under "IRC", and a new "Chat" category which includes weechat and slack?

The only potential issue I see with that is that some libraries like [pidgin](https://www.pidgin.im/) can be used with many / multiple protocols.  I don't know of a good emacs implementation of pidgin but their may be possibly a cross platform chat client in the future that can use both IRC and some other messaging platform.

**Comment by kuanyui** [comment]
2 is better I think.

> I don't know of a good emacs implementation of pidgin

You don't need to spend time to think an imaginary problem.

**Comment by rakanalh** [comment]
I think Interface Enhancements is the best option. I think navigation could be misleading in this case. and it's definitely not in project management. 

I don't see the link to Dashboard in the PR though. Are you going to push it or would you like a PR for that?

**Comment by agsdot** [comment]
@rakanalh why don't you put in a PR for that -- you created the package
after all.

@kuanyui, I'll update the categories label for IRC and Chat later.

**Comment by rakanalh** [comment]
@agsdot i did, check the two currently open PRs :)

**Pull request merged**
