### PR TITLE
Add artist mode to editing

### PR DESCRIPTION
**Pull request by suyashmahar**
This PR adds following packages:
* [artist-mode](http://cinsk.github.io//emacs/emacs-artist.html)

### CODE REVIEW

**Comment by agsdot** [comment]
@suyashmahar a couple comments:

- Why the double slash in [[http://cinsk.github.io//emacs/emacs-artist.html][artist-mode]], it resolves in my browser chrome, but https://cinsk.github.io/emacs/emacs-artist.html would be the more accurate URL.

- Where is the link to the *.el file on the cinsk.github.io page? Why not https://www.emacswiki.org/emacs/ArtistMode or http://www.lysator.liu.se/~tab/artist/ and perhaps reference or not the screencast URL you mentioned from cinsk.github.io

**Comment by suyashmahar** [comment]
@agsdot Thank you for review, I will fix this. 
Is it possible to include `CONTRIBUTING.md` file so that contributors can follow all the guidelines?

**Comment by suyashmahar** [comment]
@agsdot Fixed URL for artist-mode.

**Comment by agsdot** [comment]
Sorry, one more thing @suyashmahar . I just noticed on emacswiki that it said "It is part of Emacs (though you may need to add a require statement for it) and can also be retrieved from http://www.lysator.liu.se/~tab/artist/." (And indeed verifed it by opening up emacs and doing M-x artist-mode) Therefore, artist mode would qualify for the built in tag.

Can you change

- [[http://www.lysator.liu.se/~tab/artist/][artist-mode]] - Draw ASCII lines, squares...

to

- [[http://www.lysator.liu.se/~tab/artist/][artist-mode]] - =[built-in]= Draw ASCII lines, squares...

(Similar to how IDO has the built in tag)

**Comment by agsdot** [comment]
P.s. @kuanyui wrote up an excellent Contributions section at the bottom of README.org which mentions things such as package ordering and adding the built-in tag.

**Comment by suyashmahar** [comment]
@agsdot Thank you for cooperating with this, I have now updated according to guidelines.

Just a suggestion, if `CONTRIBUTING.md` file is present in a repo, following message is shown each time a new PR is opened. Which could be helpful for newbies.
image

**Comment by agsdot** [comment]
Thanks @suyashmahar.

With regards to a CONTRIBUTING.md file, I didn't know about that feature on github. I've wondered for a while about .github files as well and how they affect github issues and pull requests.

Anyhow soon, I'll open up another Issue to discuss creating a CONTRIBUTING.md file with @kuanyui .

**Pull request merged**
