### PR TITLE
Add yascroll-el

### PR DESCRIPTION
**Pull request by azzamsa**
This package doesn't have huge stargazers. But it really solve my long standing problem. Especially emacs users who need analog feedback of their current position.
And at the same time they disabled line-numbers and scroll-bar-mode.

[more story](https://twitter.com/_wilfredh/status/1050155492264296450)

### CODE REVIEW

**Comment by agsdot** [comment]
Thanks for contributing the PR @azzamsa . Your contributions are much appreciated.

**Comment by azzamsa** [comment]
It's been long time since my last commit here. :)

Thank you for maintaining this repo. keeping things curated.

**Comment by agsdot** [comment]
Welcome back! Your commits and contributions to awesome-emacs are most welcome.

For sure. No problem. Thanks for the compliment.

Thank you for contributing.  It's people such as yourself that keep emacs-tw/awesome-emacs and the emacs community and ecosystem vibrant and healthy.

**Comment by azzamsa** [comment]
:)

I am very happy to hear this. 

Hope you are always healthy and successful.

**Comment by agsdot** [comment]
@azzamsa Thanks. Things are going decently. 

Likewise, I hope that you are "healthy and successful" as well.

**Pull request merged**
